---
apiVersion: v1
kind: Service
metadata:
  name: quote1
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: quote1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote1
  namespace: ambassador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote1
    spec:
      containers:
      - name: backend
        image: kennethreitz/httpbin
        # image: docker.io/datawire/quote:0.4.1
        ports:
        - name: http
          containerPort: 80
